- name: frontend play
  hosts: awsservers
  become: true
  remote_user: admin

  tasks:
    - name: Mise à jour de la liste des paquets
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Installer les paquets requis de base
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Télécharger la clé GPG officielle de Docker
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Ajouter le dépôt APT stable de Docker
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable'
        state: present
        filename: docker.list

    - name: Mise à jour de la liste des paquets avec les nouveaux dépôts ajoutés
      apt:
        update_cache: yes

    - name: Installer la dernière version de Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Ajouter l'utilisateur courant au groupe docker
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes

    - name: Installer Docker Compose
      get_url:
        url: 'https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}'
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Vérifier l'installation de Docker Compose
      command: docker-compose --version
      register: docker_compose_version

    - name: Afficher la version de Docker Compose installée
      debug:
        msg: '{{ docker_compose_version.stdout }}'
